[2024-07-14T04:05:48.943+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:05:49.096+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_categories.run scheduled__2024-07-10T00:00:00+00:00 [queued]>
[2024-07-14T04:05:49.235+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_categories.run scheduled__2024-07-10T00:00:00+00:00 [queued]>
[2024-07-14T04:05:49.244+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:05:50.695+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.raw_categories.run> on 2024-07-10 00:00:00+00:00
[2024-07-14T04:05:50.743+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_categories.run', 'scheduled__2024-07-10T00:00:00+00:00', '--job-id', '1079', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpk07doct7']
[2024-07-14T04:05:50.776+0000] {standard_task_runner.py:91} INFO - Job 1079: Subtask transform.raw_categories.run
[2024-07-14T04:05:50.777+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12970) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:05:50.798+0000] {standard_task_runner.py:63} INFO - Started process 13001 to run task
[2024-07-14T04:05:50.882+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:05:51.166+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_categories.run scheduled__2024-07-10T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:05:51.930+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_categories.run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-10T00:00:00+00:00'
[2024-07-14T04:05:51.934+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:05:51.944+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:05:51.958+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpnwy6yrxu from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:05:52.007+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:05:52.271+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:05:52.280+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:05:52.293+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:05:52.330+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:05:52.344+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpnwy6yrxu', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpnwy6yrxu
[2024-07-14T04:05:52.354+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:05:52.357+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpnwy6yrxu', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:05:52.464+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:06:09.764+0000] {subprocess.py:94} INFO - [0m04:06:09  Running with dbt=1.8.3
[2024-07-14T04:06:11.507+0000] {subprocess.py:94} INFO - [0m04:06:11  Updating lock file in file path: /tmp/tmpnwy6yrxu/package-lock.yml
[2024-07-14T04:06:11.584+0000] {subprocess.py:94} INFO - [0m04:06:11  Installing dbt-labs/dbt_utils
[2024-07-14T04:06:12.716+0000] {subprocess.py:94} INFO - [0m04:06:12  Installed from version 0.8.6
[2024-07-14T04:06:12.727+0000] {subprocess.py:94} INFO - [0m04:06:12  Updated version available: 1.2.0
[2024-07-14T04:06:12.732+0000] {subprocess.py:94} INFO - [0m04:06:12
[2024-07-14T04:06:12.737+0000] {subprocess.py:94} INFO - [0m04:06:12  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:06:12.739+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:06:16.433+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:06:16.440+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:06:16.448+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_categories', '--project-dir', '/tmp/tmpnwy6yrxu', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpnwy6yrxu
[2024-07-14T04:06:16.457+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:06:16.471+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_categories', '--project-dir', '/tmp/tmpnwy6yrxu', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:06:16.560+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:06:31.718+0000] {subprocess.py:94} INFO - [0m04:06:31  Running with dbt=1.8.3
[2024-07-14T04:06:35.068+0000] {subprocess.py:94} INFO - [0m04:06:35  Registered adapter: snowflake=1.8.3
[2024-07-14T04:06:39.573+0000] {subprocess.py:94} INFO - [0m04:06:39  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:06:39.584+0000] {subprocess.py:94} INFO - [0m04:06:39
[2024-07-14T04:06:47.792+0000] {subprocess.py:94} INFO - [0m04:06:47  Concurrency: 1 threads (target='dev')
[2024-07-14T04:06:47.796+0000] {subprocess.py:94} INFO - [0m04:06:47
[2024-07-14T04:06:47.837+0000] {subprocess.py:94} INFO - [0m04:06:47  1 of 1 START sql table model raw.raw_categories ................................ [RUN]
[2024-07-14T04:06:50.707+0000] {subprocess.py:94} INFO - [0m04:06:50  1 of 1 OK created sql table model raw.raw_categories ........................... [[32mSUCCESS 1[0m in 2.85s]
[2024-07-14T04:06:50.740+0000] {subprocess.py:94} INFO - [0m04:06:50
[2024-07-14T04:06:50.744+0000] {subprocess.py:94} INFO - [0m04:06:50  Finished running 1 table model in 0 hours 0 minutes and 11.15 seconds (11.15s).
[2024-07-14T04:06:51.362+0000] {subprocess.py:94} INFO - [0m04:06:51
[2024-07-14T04:06:51.366+0000] {subprocess.py:94} INFO - [0m04:06:51  [32mCompleted successfully[0m
[2024-07-14T04:06:51.374+0000] {subprocess.py:94} INFO - [0m04:06:51
[2024-07-14T04:06:51.377+0000] {subprocess.py:94} INFO - [0m04:06:51  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:06:53.934+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:06:53.937+0000] {local.py:254} INFO - [0m04:06:51  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:06:55.161+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:06:55.169+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:06:55.208+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.PUBLIC.categories', extra=None)]
[2024-07-14T04:06:55.215+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_categories', extra=None)]
[2024-07-14T04:06:55.222+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:06:55.764+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:06:55.977+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_categories.run, run_id=scheduled__2024-07-10T00:00:00+00:00, execution_date=20240710T000000, start_date=20240714T040549, end_date=20240714T040655
[2024-07-14T04:06:56.932+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:06:56.993+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
