[2024-07-14T04:33:24.640+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:33:24.890+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_territories.run scheduled__2024-06-28T00:00:00+00:00 [queued]>
[2024-07-14T04:33:24.968+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_territories.run scheduled__2024-06-28T00:00:00+00:00 [queued]>
[2024-07-14T04:33:24.970+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:33:25.027+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.raw_territories.run> on 2024-06-28 00:00:00+00:00
[2024-07-14T04:33:25.073+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_territories.run', 'scheduled__2024-06-28T00:00:00+00:00', '--job-id', '1431', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp31p91a1z']
[2024-07-14T04:33:25.079+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=18737) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:33:25.099+0000] {standard_task_runner.py:91} INFO - Job 1431: Subtask transform.raw_territories.run
[2024-07-14T04:33:25.100+0000] {standard_task_runner.py:63} INFO - Started process 18767 to run task
[2024-07-14T04:33:25.237+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:33:25.506+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_territories.run scheduled__2024-06-28T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:33:26.121+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_territories.run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-28T00:00:00+00:00'
[2024-07-14T04:33:26.131+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:33:26.138+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:33:26.146+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpzsfmdp6c from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:33:26.169+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:33:27.571+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:33:27.572+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:33:27.576+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:33:27.590+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:33:27.599+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpzsfmdp6c', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpzsfmdp6c
[2024-07-14T04:33:27.608+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:33:27.615+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpzsfmdp6c', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:33:27.699+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:33:44.517+0000] {subprocess.py:94} INFO - [0m04:33:44  Running with dbt=1.8.3
[2024-07-14T04:33:47.073+0000] {subprocess.py:94} INFO - [0m04:33:47  Updating lock file in file path: /tmp/tmpzsfmdp6c/package-lock.yml
[2024-07-14T04:33:47.120+0000] {subprocess.py:94} INFO - [0m04:33:47  Installing dbt-labs/dbt_utils
[2024-07-14T04:33:48.630+0000] {subprocess.py:94} INFO - [0m04:33:48  Installed from version 0.8.6
[2024-07-14T04:33:48.637+0000] {subprocess.py:94} INFO - [0m04:33:48  Updated version available: 1.2.0
[2024-07-14T04:33:48.653+0000] {subprocess.py:94} INFO - [0m04:33:48
[2024-07-14T04:33:48.674+0000] {subprocess.py:94} INFO - [0m04:33:48  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:33:48.677+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:33:51.570+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:33:51.573+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:33:51.576+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_territories', '--project-dir', '/tmp/tmpzsfmdp6c', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpzsfmdp6c
[2024-07-14T04:33:51.579+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:33:51.584+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_territories', '--project-dir', '/tmp/tmpzsfmdp6c', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:33:51.717+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:34:05.319+0000] {subprocess.py:94} INFO - [0m04:34:05  Running with dbt=1.8.3
[2024-07-14T04:34:09.455+0000] {subprocess.py:94} INFO - [0m04:34:09  Registered adapter: snowflake=1.8.3
[2024-07-14T04:34:14.359+0000] {subprocess.py:94} INFO - [0m04:34:14  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:34:14.367+0000] {subprocess.py:94} INFO - [0m04:34:14
[2024-07-14T04:34:23.635+0000] {subprocess.py:94} INFO - [0m04:34:23  Concurrency: 1 threads (target='dev')
[2024-07-14T04:34:23.640+0000] {subprocess.py:94} INFO - [0m04:34:23
[2024-07-14T04:34:23.816+0000] {subprocess.py:94} INFO - [0m04:34:23  1 of 1 START sql table model raw.raw_territories ............................... [RUN]
[2024-07-14T04:34:27.384+0000] {subprocess.py:94} INFO - [0m04:34:27  1 of 1 OK created sql table model raw.raw_territories .......................... [[32mSUCCESS 1[0m in 3.56s]
[2024-07-14T04:34:27.443+0000] {subprocess.py:94} INFO - [0m04:34:27
[2024-07-14T04:34:27.446+0000] {subprocess.py:94} INFO - [0m04:34:27  Finished running 1 table model in 0 hours 0 minutes and 13.07 seconds (13.07s).
[2024-07-14T04:34:28.411+0000] {subprocess.py:94} INFO - [0m04:34:28
[2024-07-14T04:34:28.415+0000] {subprocess.py:94} INFO - [0m04:34:28  [32mCompleted successfully[0m
[2024-07-14T04:34:28.434+0000] {subprocess.py:94} INFO - [0m04:34:28
[2024-07-14T04:34:28.442+0000] {subprocess.py:94} INFO - [0m04:34:28  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:34:30.808+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:34:30.811+0000] {local.py:254} INFO - [0m04:34:28  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:34:30.898+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:34:30.918+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:34:30.959+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.PUBLIC.territories', extra=None)]
[2024-07-14T04:34:30.961+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_territories', extra=None)]
[2024-07-14T04:34:30.964+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:34:31.302+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:34:31.588+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_territories.run, run_id=scheduled__2024-06-28T00:00:00+00:00, execution_date=20240628T000000, start_date=20240714T043324, end_date=20240714T043431
[2024-07-14T04:34:32.995+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:34:33.387+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:34:33.402+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
