[2024-07-14T03:25:55.507+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T03:25:55.596+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_categories.run manual__2024-07-14T03:25:17.009601+00:00 [queued]>
[2024-07-14T03:25:55.642+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_categories.run manual__2024-07-14T03:25:17.009601+00:00 [queued]>
[2024-07-14T03:25:55.643+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T03:25:55.686+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.raw_categories.run> on 2024-07-14 03:25:17.009601+00:00
[2024-07-14T03:25:55.710+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6872) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T03:25:55.712+0000] {standard_task_runner.py:63} INFO - Started process 6894 to run task
[2024-07-14T03:25:55.714+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_categories.run', 'manual__2024-07-14T03:25:17.009601+00:00', '--job-id', '577', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpgk3sshsd']
[2024-07-14T03:25:55.723+0000] {standard_task_runner.py:91} INFO - Job 577: Subtask transform.raw_categories.run
[2024-07-14T03:25:55.786+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T03:25:55.989+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_categories.run manual__2024-07-14T03:25:17.009601+00:00 [running]> on host airflow-scheduler
[2024-07-14T03:25:56.398+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_categories.run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T03:25:17.009601+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-14T03:25:17.009601+00:00'
[2024-07-14T03:25:56.403+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T03:25:56.413+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T03:25:56.435+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmp66uka_vq from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T03:25:56.477+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T03:25:57.089+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T03:25:57.091+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T03:25:57.094+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T03:25:57.101+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T03:25:57.104+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp66uka_vq', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp66uka_vq
[2024-07-14T03:25:57.106+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T03:25:57.109+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp66uka_vq', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T03:25:57.163+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T03:26:08.543+0000] {subprocess.py:94} INFO - [0m03:26:08  Running with dbt=1.8.3
[2024-07-14T03:26:09.944+0000] {subprocess.py:94} INFO - [0m03:26:09  Updating lock file in file path: /tmp/tmp66uka_vq/package-lock.yml
[2024-07-14T03:26:09.971+0000] {subprocess.py:94} INFO - [0m03:26:09  Installing dbt-labs/dbt_utils
[2024-07-14T03:26:14.566+0000] {subprocess.py:94} INFO - [0m03:26:14  Installed from version 0.8.6
[2024-07-14T03:26:14.569+0000] {subprocess.py:94} INFO - [0m03:26:14  Updated version available: 1.2.0
[2024-07-14T03:26:14.572+0000] {subprocess.py:94} INFO - [0m03:26:14
[2024-07-14T03:26:14.575+0000] {subprocess.py:94} INFO - [0m03:26:14  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T03:26:14.578+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T03:26:16.666+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T03:26:16.670+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T03:26:16.677+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_categories', '--project-dir', '/tmp/tmp66uka_vq', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp66uka_vq
[2024-07-14T03:26:16.683+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T03:26:16.690+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_categories', '--project-dir', '/tmp/tmp66uka_vq', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T03:26:16.777+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T03:26:29.538+0000] {subprocess.py:94} INFO - [0m03:26:29  Running with dbt=1.8.3
[2024-07-14T03:26:31.692+0000] {subprocess.py:94} INFO - [0m03:26:31  Registered adapter: snowflake=1.8.3
[2024-07-14T03:26:39.289+0000] {subprocess.py:94} INFO - [0m03:26:39  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T03:26:39.303+0000] {subprocess.py:94} INFO - [0m03:26:39
[2024-07-14T03:26:47.372+0000] {subprocess.py:94} INFO - [0m03:26:47  Concurrency: 1 threads (target='dev')
[2024-07-14T03:26:47.377+0000] {subprocess.py:94} INFO - [0m03:26:47
[2024-07-14T03:26:47.440+0000] {subprocess.py:94} INFO - [0m03:26:47  1 of 1 START sql table model raw.raw_categories ................................ [RUN]
[2024-07-14T03:26:49.807+0000] {subprocess.py:94} INFO - [0m03:26:49  1 of 1 OK created sql table model raw.raw_categories ........................... [[32mSUCCESS 1[0m in 2.35s]
[2024-07-14T03:26:49.831+0000] {subprocess.py:94} INFO - [0m03:26:49
[2024-07-14T03:26:49.836+0000] {subprocess.py:94} INFO - [0m03:26:49  Finished running 1 table model in 0 hours 0 minutes and 10.52 seconds (10.52s).
[2024-07-14T03:26:50.057+0000] {subprocess.py:94} INFO - [0m03:26:50
[2024-07-14T03:26:50.059+0000] {subprocess.py:94} INFO - [0m03:26:50  [32mCompleted successfully[0m
[2024-07-14T03:26:50.061+0000] {subprocess.py:94} INFO - [0m03:26:50
[2024-07-14T03:26:50.063+0000] {subprocess.py:94} INFO - [0m03:26:50  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T03:26:52.226+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T03:26:52.230+0000] {local.py:254} INFO - [0m03:26:50  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T03:26:52.389+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T03:26:52.392+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T03:26:52.439+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.PUBLIC.categories', extra=None)]
[2024-07-14T03:26:52.452+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_categories', extra=None)]
[2024-07-14T03:26:52.490+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T03:26:52.707+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to None, run_after=None
[2024-07-14T03:26:52.940+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T03:26:53.201+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_categories.run, run_id=manual__2024-07-14T03:25:17.009601+00:00, execution_date=20240714T032517, start_date=20240714T032555, end_date=20240714T032653
[2024-07-14T03:26:53.369+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T03:26:53.427+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
