[2024-07-14T04:17:02.769+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:17:03.158+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_suppliers.test scheduled__2024-06-30T00:00:00+00:00 [queued]>
[2024-07-14T04:17:03.261+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_suppliers.test scheduled__2024-06-30T00:00:00+00:00 [queued]>
[2024-07-14T04:17:03.280+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:17:03.562+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.dim_suppliers.test> on 2024-06-30 00:00:00+00:00
[2024-07-14T04:17:03.624+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=15415) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:17:03.643+0000] {standard_task_runner.py:63} INFO - Started process 15448 to run task
[2024-07-14T04:17:03.651+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.dim_suppliers.test', 'scheduled__2024-06-30T00:00:00+00:00', '--job-id', '1231', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp771magc7']
[2024-07-14T04:17:03.684+0000] {standard_task_runner.py:91} INFO - Job 1231: Subtask transform.dim_suppliers.test
[2024-07-14T04:17:03.810+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:17:04.140+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.dim_suppliers.test scheduled__2024-06-30T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:17:04.967+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.dim_suppliers.test' AIRFLOW_CTX_EXECUTION_DATE='2024-06-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-30T00:00:00+00:00'
[2024-07-14T04:17:04.978+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:17:05.004+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:17:05.033+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmp5cba248g from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:17:05.079+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:17:05.322+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:17:05.339+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:17:05.345+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:17:05.353+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:17:05.367+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp5cba248g', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp5cba248g
[2024-07-14T04:17:05.379+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:17:05.389+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp5cba248g', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:17:05.451+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:17:19.563+0000] {subprocess.py:94} INFO - [0m04:17:19  Running with dbt=1.8.3
[2024-07-14T04:17:21.352+0000] {subprocess.py:94} INFO - [0m04:17:21  Updating lock file in file path: /tmp/tmp5cba248g/package-lock.yml
[2024-07-14T04:17:21.393+0000] {subprocess.py:94} INFO - [0m04:17:21  Installing dbt-labs/dbt_utils
[2024-07-14T04:17:22.227+0000] {subprocess.py:94} INFO - [0m04:17:22  Installed from version 0.8.6
[2024-07-14T04:17:22.232+0000] {subprocess.py:94} INFO - [0m04:17:22  Updated version available: 1.2.0
[2024-07-14T04:17:22.247+0000] {subprocess.py:94} INFO - [0m04:17:22
[2024-07-14T04:17:22.253+0000] {subprocess.py:94} INFO - [0m04:17:22  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:17:22.255+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:17:25.123+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:17:25.125+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:17:25.128+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'dim_suppliers', '--project-dir', '/tmp/tmp5cba248g', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp5cba248g
[2024-07-14T04:17:25.134+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:17:25.137+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'dim_suppliers', '--project-dir', '/tmp/tmp5cba248g', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:17:25.236+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:17:39.118+0000] {subprocess.py:94} INFO - [0m04:17:39  Running with dbt=1.8.3
[2024-07-14T04:17:43.773+0000] {subprocess.py:94} INFO - [0m04:17:43  Registered adapter: snowflake=1.8.3
[2024-07-14T04:17:50.014+0000] {subprocess.py:94} INFO - [0m04:17:50  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:17:50.054+0000] {subprocess.py:94} INFO - [0m04:17:50
[2024-07-14T04:17:57.571+0000] {subprocess.py:94} INFO - [0m04:17:57  Concurrency: 1 threads (target='dev')
[2024-07-14T04:17:57.583+0000] {subprocess.py:94} INFO - [0m04:17:57
[2024-07-14T04:17:57.680+0000] {subprocess.py:94} INFO - [0m04:17:57  1 of 1 START test not_null_dim_suppliers_SUPPLIERID ............................ [RUN]
[2024-07-14T04:17:59.586+0000] {subprocess.py:94} INFO - [0m04:17:59  1 of 1 PASS not_null_dim_suppliers_SUPPLIERID .................................. [[32mPASS[0m in 1.90s]
[2024-07-14T04:17:59.599+0000] {subprocess.py:94} INFO - [0m04:17:59
[2024-07-14T04:17:59.602+0000] {subprocess.py:94} INFO - [0m04:17:59  Finished running 1 test in 0 hours 0 minutes and 9.52 seconds (9.52s).
[2024-07-14T04:18:00.189+0000] {subprocess.py:94} INFO - [0m04:18:00
[2024-07-14T04:18:00.198+0000] {subprocess.py:94} INFO - [0m04:18:00  [32mCompleted successfully[0m
[2024-07-14T04:18:00.202+0000] {subprocess.py:94} INFO - [0m04:18:00
[2024-07-14T04:18:00.220+0000] {subprocess.py:94} INFO - [0m04:18:00  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:18:03.678+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:18:03.682+0000] {local.py:254} INFO - [0m04:18:00  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:18:04.792+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:18:04.795+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:18:04.831+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_suppliers', extra=None)]
[2024-07-14T04:18:04.857+0000] {local.py:350} INFO - Outlets: []
[2024-07-14T04:18:04.882+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:18:05.961+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:18:06.267+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.dim_suppliers.test, run_id=scheduled__2024-06-30T00:00:00+00:00, execution_date=20240630T000000, start_date=20240714T041703, end_date=20240714T041806
[2024-07-14T04:18:06.430+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:18:06.862+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:18:06.914+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
