[2024-07-14T04:16:49.750+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:16:49.949+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_orders.test scheduled__2024-06-28T00:00:00+00:00 [queued]>
[2024-07-14T04:16:50.033+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_orders.test scheduled__2024-06-28T00:00:00+00:00 [queued]>
[2024-07-14T04:16:50.035+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:16:50.163+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.raw_orders.test> on 2024-06-28 00:00:00+00:00
[2024-07-14T04:16:50.200+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=15374) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:16:50.204+0000] {standard_task_runner.py:63} INFO - Started process 15400 to run task
[2024-07-14T04:16:50.244+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_orders.test', 'scheduled__2024-06-28T00:00:00+00:00', '--job-id', '1224', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpmnwzxw6p']
[2024-07-14T04:16:50.258+0000] {standard_task_runner.py:91} INFO - Job 1224: Subtask transform.raw_orders.test
[2024-07-14T04:16:50.363+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:16:50.610+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_orders.test scheduled__2024-06-28T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:16:51.417+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_orders.test' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-28T00:00:00+00:00'
[2024-07-14T04:16:51.423+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:16:51.458+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:16:51.489+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmph12wjofd from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:16:51.538+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:16:51.813+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:16:51.828+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:16:51.838+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:16:51.851+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:16:51.858+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmph12wjofd', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmph12wjofd
[2024-07-14T04:16:51.868+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:16:51.879+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmph12wjofd', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:16:52.007+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:17:09.103+0000] {subprocess.py:94} INFO - [0m04:17:09  Running with dbt=1.8.3
[2024-07-14T04:17:11.378+0000] {subprocess.py:94} INFO - [0m04:17:11  Updating lock file in file path: /tmp/tmph12wjofd/package-lock.yml
[2024-07-14T04:17:11.428+0000] {subprocess.py:94} INFO - [0m04:17:11  Installing dbt-labs/dbt_utils
[2024-07-14T04:17:12.199+0000] {subprocess.py:94} INFO - [0m04:17:12  Installed from version 0.8.6
[2024-07-14T04:17:12.206+0000] {subprocess.py:94} INFO - [0m04:17:12  Updated version available: 1.2.0
[2024-07-14T04:17:12.212+0000] {subprocess.py:94} INFO - [0m04:17:12
[2024-07-14T04:17:12.216+0000] {subprocess.py:94} INFO - [0m04:17:12  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:17:12.225+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:17:14.304+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:17:14.306+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:17:14.309+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_orders', '--project-dir', '/tmp/tmph12wjofd', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmph12wjofd
[2024-07-14T04:17:14.311+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:17:14.313+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_orders', '--project-dir', '/tmp/tmph12wjofd', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:17:14.408+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:17:30.504+0000] {subprocess.py:94} INFO - [0m04:17:30  Running with dbt=1.8.3
[2024-07-14T04:17:34.842+0000] {subprocess.py:94} INFO - [0m04:17:34  Registered adapter: snowflake=1.8.3
[2024-07-14T04:17:41.245+0000] {subprocess.py:94} INFO - [0m04:17:41  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:17:41.282+0000] {subprocess.py:94} INFO - [0m04:17:41
[2024-07-14T04:17:52.135+0000] {subprocess.py:94} INFO - [0m04:17:52  Concurrency: 1 threads (target='dev')
[2024-07-14T04:17:52.142+0000] {subprocess.py:94} INFO - [0m04:17:52
[2024-07-14T04:17:52.331+0000] {subprocess.py:94} INFO - [0m04:17:52  1 of 1 START test not_null_raw_orders_ORDERID .................................. [RUN]
[2024-07-14T04:17:54.739+0000] {subprocess.py:94} INFO - [0m04:17:54  1 of 1 PASS not_null_raw_orders_ORDERID ........................................ [[32mPASS[0m in 2.40s]
[2024-07-14T04:17:54.752+0000] {subprocess.py:94} INFO - [0m04:17:54
[2024-07-14T04:17:54.754+0000] {subprocess.py:94} INFO - [0m04:17:54  Finished running 1 test in 0 hours 0 minutes and 13.46 seconds (13.46s).
[2024-07-14T04:17:55.237+0000] {subprocess.py:94} INFO - [0m04:17:55
[2024-07-14T04:17:55.240+0000] {subprocess.py:94} INFO - [0m04:17:55  [32mCompleted successfully[0m
[2024-07-14T04:17:55.244+0000] {subprocess.py:94} INFO - [0m04:17:55
[2024-07-14T04:17:55.246+0000] {subprocess.py:94} INFO - [0m04:17:55  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:17:57.178+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:17:57.180+0000] {local.py:254} INFO - [0m04:17:55  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:17:57.897+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:17:57.902+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:17:57.926+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_orders', extra=None)]
[2024-07-14T04:17:57.930+0000] {local.py:350} INFO - Outlets: []
[2024-07-14T04:17:57.934+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:17:58.176+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:17:58.272+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_orders.test, run_id=scheduled__2024-06-28T00:00:00+00:00, execution_date=20240628T000000, start_date=20240714T041649, end_date=20240714T041758
[2024-07-14T04:17:58.385+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:17:58.426+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
