[2024-07-14T04:07:36.171+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:07:36.293+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_employees.test scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-14T04:07:36.367+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_employees.test scheduled__2024-07-02T00:00:00+00:00 [queued]>
[2024-07-14T04:07:36.368+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:07:36.441+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.raw_employees.test> on 2024-07-02 00:00:00+00:00
[2024-07-14T04:07:36.461+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=13351) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:07:36.482+0000] {standard_task_runner.py:63} INFO - Started process 13366 to run task
[2024-07-14T04:07:36.475+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_employees.test', 'scheduled__2024-07-02T00:00:00+00:00', '--job-id', '1103', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpwx98mcfp']
[2024-07-14T04:07:36.500+0000] {standard_task_runner.py:91} INFO - Job 1103: Subtask transform.raw_employees.test
[2024-07-14T04:07:36.628+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:07:36.892+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_employees.test scheduled__2024-07-02T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:07:37.724+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_employees.test' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T00:00:00+00:00'
[2024-07-14T04:07:37.727+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:07:37.731+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:07:37.734+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpwk5qahk5 from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:07:37.751+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:07:37.887+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:07:37.901+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:07:37.903+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:07:37.921+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:07:37.925+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpwk5qahk5', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpwk5qahk5
[2024-07-14T04:07:37.928+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:07:37.930+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpwk5qahk5', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:07:37.992+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:07:51.171+0000] {subprocess.py:94} INFO - [0m04:07:51  Running with dbt=1.8.3
[2024-07-14T04:07:52.644+0000] {subprocess.py:94} INFO - [0m04:07:52  Updating lock file in file path: /tmp/tmpwk5qahk5/package-lock.yml
[2024-07-14T04:07:52.674+0000] {subprocess.py:94} INFO - [0m04:07:52  Installing dbt-labs/dbt_utils
[2024-07-14T04:07:53.390+0000] {subprocess.py:94} INFO - [0m04:07:53  Installed from version 0.8.6
[2024-07-14T04:07:53.396+0000] {subprocess.py:94} INFO - [0m04:07:53  Updated version available: 1.2.0
[2024-07-14T04:07:53.405+0000] {subprocess.py:94} INFO - [0m04:07:53
[2024-07-14T04:07:53.409+0000] {subprocess.py:94} INFO - [0m04:07:53  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:07:53.413+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:07:55.640+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:07:55.644+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:07:55.647+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_employees', '--project-dir', '/tmp/tmpwk5qahk5', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpwk5qahk5
[2024-07-14T04:07:55.660+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:07:55.685+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_employees', '--project-dir', '/tmp/tmpwk5qahk5', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:07:55.751+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:08:07.198+0000] {subprocess.py:94} INFO - [0m04:08:07  Running with dbt=1.8.3
[2024-07-14T04:08:10.521+0000] {subprocess.py:94} INFO - [0m04:08:10  Registered adapter: snowflake=1.8.3
[2024-07-14T04:08:15.072+0000] {subprocess.py:94} INFO - [0m04:08:15  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:08:15.083+0000] {subprocess.py:94} INFO - [0m04:08:15
[2024-07-14T04:08:22.665+0000] {subprocess.py:94} INFO - [0m04:08:22  Concurrency: 1 threads (target='dev')
[2024-07-14T04:08:22.676+0000] {subprocess.py:94} INFO - [0m04:08:22
[2024-07-14T04:08:22.934+0000] {subprocess.py:94} INFO - [0m04:08:22  1 of 1 START test not_null_raw_employees_EMPLOYEEID ............................ [RUN]
[2024-07-14T04:08:25.264+0000] {subprocess.py:94} INFO - [0m04:08:25  1 of 1 PASS not_null_raw_employees_EMPLOYEEID .................................. [[32mPASS[0m in 2.33s]
[2024-07-14T04:08:25.289+0000] {subprocess.py:94} INFO - [0m04:08:25
[2024-07-14T04:08:25.293+0000] {subprocess.py:94} INFO - [0m04:08:25  Finished running 1 test in 0 hours 0 minutes and 10.20 seconds (10.20s).
[2024-07-14T04:08:25.977+0000] {subprocess.py:94} INFO - [0m04:08:25
[2024-07-14T04:08:25.986+0000] {subprocess.py:94} INFO - [0m04:08:25  [32mCompleted successfully[0m
[2024-07-14T04:08:25.993+0000] {subprocess.py:94} INFO - [0m04:08:25
[2024-07-14T04:08:25.996+0000] {subprocess.py:94} INFO - [0m04:08:25  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:08:28.284+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:08:28.290+0000] {local.py:254} INFO - [0m04:08:25  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:08:29.209+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:08:29.213+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:08:29.249+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_employees', extra=None)]
[2024-07-14T04:08:29.264+0000] {local.py:350} INFO - Outlets: []
[2024-07-14T04:08:29.285+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:08:29.573+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:08:29.747+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_employees.test, run_id=scheduled__2024-07-02T00:00:00+00:00, execution_date=20240702T000000, start_date=20240714T040736, end_date=20240714T040829
[2024-07-14T04:08:30.647+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:08:30.804+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:08:30.839+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
