[2024-07-14T03:50:39.428+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T03:50:39.502+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_products.run manual__2024-07-14T03:47:05.410676+00:00 [queued]>
[2024-07-14T03:50:39.549+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_products.run manual__2024-07-14T03:47:05.410676+00:00 [queued]>
[2024-07-14T03:50:39.551+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T03:50:39.599+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.dim_products.run> on 2024-07-14 03:47:05.410676+00:00
[2024-07-14T03:50:39.630+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=9055) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T03:50:39.626+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.dim_products.run', 'manual__2024-07-14T03:47:05.410676+00:00', '--job-id', '663', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpn9qh4y01']
[2024-07-14T03:50:39.636+0000] {standard_task_runner.py:63} INFO - Started process 9058 to run task
[2024-07-14T03:50:39.637+0000] {standard_task_runner.py:91} INFO - Job 663: Subtask transform.dim_products.run
[2024-07-14T03:50:39.709+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T03:50:39.872+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.dim_products.run manual__2024-07-14T03:47:05.410676+00:00 [running]> on host airflow-scheduler
[2024-07-14T03:50:40.306+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.dim_products.run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T03:47:05.410676+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-14T03:47:05.410676+00:00'
[2024-07-14T03:50:40.313+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T03:50:40.320+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T03:50:40.325+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpbq3_6kzx from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T03:50:40.351+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T03:50:40.870+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T03:50:40.872+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T03:50:40.873+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T03:50:40.877+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T03:50:40.879+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpbq3_6kzx', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpbq3_6kzx
[2024-07-14T03:50:40.882+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T03:50:40.884+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpbq3_6kzx', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T03:50:40.906+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T03:50:46.031+0000] {subprocess.py:94} INFO - [0m03:50:46  Running with dbt=1.8.3
[2024-07-14T03:50:46.740+0000] {subprocess.py:94} INFO - [0m03:50:46  Updating lock file in file path: /tmp/tmpbq3_6kzx/package-lock.yml
[2024-07-14T03:50:46.780+0000] {subprocess.py:94} INFO - [0m03:50:46  Installing dbt-labs/dbt_utils
[2024-07-14T03:50:47.463+0000] {subprocess.py:94} INFO - [0m03:50:47  Installed from version 0.8.6
[2024-07-14T03:50:47.465+0000] {subprocess.py:94} INFO - [0m03:50:47  Updated version available: 1.2.0
[2024-07-14T03:50:47.467+0000] {subprocess.py:94} INFO - [0m03:50:47
[2024-07-14T03:50:47.469+0000] {subprocess.py:94} INFO - [0m03:50:47  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T03:50:47.471+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T03:50:50.851+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T03:50:50.853+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T03:50:50.855+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'dim_products', '--project-dir', '/tmp/tmpbq3_6kzx', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpbq3_6kzx
[2024-07-14T03:50:50.858+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T03:50:50.861+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'dim_products', '--project-dir', '/tmp/tmpbq3_6kzx', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T03:50:50.882+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T03:50:56.945+0000] {subprocess.py:94} INFO - [0m03:50:56  Running with dbt=1.8.3
[2024-07-14T03:50:58.483+0000] {subprocess.py:94} INFO - [0m03:50:58  Registered adapter: snowflake=1.8.3
[2024-07-14T03:51:01.597+0000] {subprocess.py:94} INFO - [0m03:51:01  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T03:51:01.605+0000] {subprocess.py:94} INFO - [0m03:51:01
[2024-07-14T03:51:09.592+0000] {subprocess.py:94} INFO - [0m03:51:09  Concurrency: 1 threads (target='dev')
[2024-07-14T03:51:09.596+0000] {subprocess.py:94} INFO - [0m03:51:09
[2024-07-14T03:51:09.644+0000] {subprocess.py:94} INFO - [0m03:51:09  1 of 1 START sql table model dwh.dim_products .................................. [RUN]
[2024-07-14T03:51:12.650+0000] {subprocess.py:94} INFO - [0m03:51:12  1 of 1 OK created sql table model dwh.dim_products ............................. [[32mSUCCESS 1[0m in 2.99s]
[2024-07-14T03:51:12.677+0000] {subprocess.py:94} INFO - [0m03:51:12
[2024-07-14T03:51:12.681+0000] {subprocess.py:94} INFO - [0m03:51:12  Finished running 1 table model in 0 hours 0 minutes and 11.07 seconds (11.07s).
[2024-07-14T03:51:13.065+0000] {subprocess.py:94} INFO - [0m03:51:13
[2024-07-14T03:51:13.092+0000] {subprocess.py:94} INFO - [0m03:51:13  [32mCompleted successfully[0m
[2024-07-14T03:51:13.094+0000] {subprocess.py:94} INFO - [0m03:51:13
[2024-07-14T03:51:13.098+0000] {subprocess.py:94} INFO - [0m03:51:13  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T03:51:15.012+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T03:51:15.014+0000] {local.py:254} INFO - [0m03:51:13  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T03:51:15.085+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T03:51:15.086+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T03:51:15.101+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_categories', extra=None), Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_suppliers', extra=None), Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_products', extra=None)]
[2024-07-14T03:51:15.103+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_products', extra=None)]
[2024-07-14T03:51:15.106+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T03:51:15.161+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to None, run_after=None
[2024-07-14T03:51:15.296+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T03:51:15.397+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.dim_products.run, run_id=manual__2024-07-14T03:47:05.410676+00:00, execution_date=20240714T034705, start_date=20240714T035039, end_date=20240714T035115
[2024-07-14T03:51:15.482+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T03:51:15.511+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
