[2024-07-14T04:09:28.178+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:09:28.349+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_suppliers.test scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-14T04:09:28.411+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_suppliers.test scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-14T04:09:28.412+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:09:28.501+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.raw_suppliers.test> on 2024-07-11 00:00:00+00:00
[2024-07-14T04:09:28.532+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=13761) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:09:28.542+0000] {standard_task_runner.py:63} INFO - Started process 13795 to run task
[2024-07-14T04:09:28.550+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_suppliers.test', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '1130', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmphiwj3a65']
[2024-07-14T04:09:28.564+0000] {standard_task_runner.py:91} INFO - Job 1130: Subtask transform.raw_suppliers.test
[2024-07-14T04:09:28.724+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:09:29.022+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_suppliers.test scheduled__2024-07-11T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:09:29.651+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_suppliers.test' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-14T04:09:29.655+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:09:29.666+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:09:29.672+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpdwuv8iew from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:09:29.704+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:09:29.891+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:09:29.901+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:09:29.908+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:09:29.914+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:09:29.916+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpdwuv8iew', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpdwuv8iew
[2024-07-14T04:09:29.929+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:09:29.932+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpdwuv8iew', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:09:30.016+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:09:46.634+0000] {subprocess.py:94} INFO - [0m04:09:46  Running with dbt=1.8.3
[2024-07-14T04:09:48.962+0000] {subprocess.py:94} INFO - [0m04:09:48  Updating lock file in file path: /tmp/tmpdwuv8iew/package-lock.yml
[2024-07-14T04:09:49.021+0000] {subprocess.py:94} INFO - [0m04:09:49  Installing dbt-labs/dbt_utils
[2024-07-14T04:09:50.057+0000] {subprocess.py:94} INFO - [0m04:09:50  Installed from version 0.8.6
[2024-07-14T04:09:50.060+0000] {subprocess.py:94} INFO - [0m04:09:50  Updated version available: 1.2.0
[2024-07-14T04:09:50.066+0000] {subprocess.py:94} INFO - [0m04:09:50
[2024-07-14T04:09:50.082+0000] {subprocess.py:94} INFO - [0m04:09:50  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:09:50.085+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:09:52.372+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:09:52.374+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:09:52.376+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_suppliers', '--project-dir', '/tmp/tmpdwuv8iew', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpdwuv8iew
[2024-07-14T04:09:52.379+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:09:52.381+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_suppliers', '--project-dir', '/tmp/tmpdwuv8iew', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:09:52.465+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:10:05.862+0000] {subprocess.py:94} INFO - [0m04:10:05  Running with dbt=1.8.3
[2024-07-14T04:10:09.706+0000] {subprocess.py:94} INFO - [0m04:10:09  Registered adapter: snowflake=1.8.3
[2024-07-14T04:10:15.082+0000] {subprocess.py:94} INFO - [0m04:10:15  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:10:15.086+0000] {subprocess.py:94} INFO - [0m04:10:15
[2024-07-14T04:10:21.180+0000] {subprocess.py:94} INFO - [0m04:10:21  Concurrency: 1 threads (target='dev')
[2024-07-14T04:10:21.185+0000] {subprocess.py:94} INFO - [0m04:10:21
[2024-07-14T04:10:21.371+0000] {subprocess.py:94} INFO - [0m04:10:21  1 of 1 START test not_null_raw_suppliers_SUPPLIERID ............................ [RUN]
[2024-07-14T04:10:23.405+0000] {subprocess.py:94} INFO - [0m04:10:23  1 of 1 PASS not_null_raw_suppliers_SUPPLIERID .................................. [[32mPASS[0m in 2.03s]
[2024-07-14T04:10:23.431+0000] {subprocess.py:94} INFO - [0m04:10:23
[2024-07-14T04:10:23.436+0000] {subprocess.py:94} INFO - [0m04:10:23  Finished running 1 test in 0 hours 0 minutes and 8.34 seconds (8.34s).
[2024-07-14T04:10:24.214+0000] {subprocess.py:94} INFO - [0m04:10:24
[2024-07-14T04:10:24.219+0000] {subprocess.py:94} INFO - [0m04:10:24  [32mCompleted successfully[0m
[2024-07-14T04:10:24.223+0000] {subprocess.py:94} INFO - [0m04:10:24
[2024-07-14T04:10:24.227+0000] {subprocess.py:94} INFO - [0m04:10:24  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:10:27.027+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:10:27.030+0000] {local.py:254} INFO - [0m04:10:24  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:10:28.461+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:10:28.475+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:10:28.530+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_suppliers', extra=None)]
[2024-07-14T04:10:28.535+0000] {local.py:350} INFO - Outlets: []
[2024-07-14T04:10:28.549+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:10:28.894+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:10:29.144+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_suppliers.test, run_id=scheduled__2024-07-11T00:00:00+00:00, execution_date=20240711T000000, start_date=20240714T040928, end_date=20240714T041029
[2024-07-14T04:10:31.567+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:10:31.673+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
