[2024-07-14T04:24:20.271+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:24:20.434+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_products.run scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-07-14T04:24:20.652+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_products.run scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-07-14T04:24:20.653+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:24:20.826+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.dim_products.run> on 2024-07-05 00:00:00+00:00
[2024-07-14T04:24:20.883+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=16898) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:24:20.886+0000] {standard_task_runner.py:63} INFO - Started process 16940 to run task
[2024-07-14T04:24:20.961+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.dim_products.run', 'scheduled__2024-07-05T00:00:00+00:00', '--job-id', '1320', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpead6_etb']
[2024-07-14T04:24:20.990+0000] {standard_task_runner.py:91} INFO - Job 1320: Subtask transform.dim_products.run
[2024-07-14T04:24:21.180+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:24:21.374+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.dim_products.run scheduled__2024-07-05T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:24:21.928+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.dim_products.run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-05T00:00:00+00:00'
[2024-07-14T04:24:21.944+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:24:21.973+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:24:21.997+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpxk3d2lxj from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:24:22.082+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:24:22.340+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:24:22.353+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:24:22.355+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:24:22.365+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:24:22.377+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpxk3d2lxj', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpxk3d2lxj
[2024-07-14T04:24:22.390+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:24:22.392+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpxk3d2lxj', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:24:22.589+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:24:38.481+0000] {subprocess.py:94} INFO - [0m04:24:38  Running with dbt=1.8.3
[2024-07-14T04:24:39.929+0000] {subprocess.py:94} INFO - [0m04:24:39  Updating lock file in file path: /tmp/tmpxk3d2lxj/package-lock.yml
[2024-07-14T04:24:39.992+0000] {subprocess.py:94} INFO - [0m04:24:39  Installing dbt-labs/dbt_utils
[2024-07-14T04:24:40.959+0000] {subprocess.py:94} INFO - [0m04:24:40  Installed from version 0.8.6
[2024-07-14T04:24:40.967+0000] {subprocess.py:94} INFO - [0m04:24:40  Updated version available: 1.2.0
[2024-07-14T04:24:40.973+0000] {subprocess.py:94} INFO - [0m04:24:40
[2024-07-14T04:24:40.995+0000] {subprocess.py:94} INFO - [0m04:24:40  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:24:41.000+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:24:43.451+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:24:43.454+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:24:43.456+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'dim_products', '--project-dir', '/tmp/tmpxk3d2lxj', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpxk3d2lxj
[2024-07-14T04:24:43.458+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:24:43.477+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'dim_products', '--project-dir', '/tmp/tmpxk3d2lxj', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:24:43.530+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:25:00.946+0000] {subprocess.py:94} INFO - [0m04:25:00  Running with dbt=1.8.3
[2024-07-14T04:25:04.629+0000] {subprocess.py:94} INFO - [0m04:25:04  Registered adapter: snowflake=1.8.3
[2024-07-14T04:25:09.629+0000] {subprocess.py:94} INFO - [0m04:25:09  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:25:09.653+0000] {subprocess.py:94} INFO - [0m04:25:09
[2024-07-14T04:25:18.443+0000] {subprocess.py:94} INFO - [0m04:25:18  Concurrency: 1 threads (target='dev')
[2024-07-14T04:25:18.445+0000] {subprocess.py:94} INFO - [0m04:25:18
[2024-07-14T04:25:18.581+0000] {subprocess.py:94} INFO - [0m04:25:18  1 of 1 START sql table model dwh.dim_products .................................. [RUN]
[2024-07-14T04:25:21.839+0000] {subprocess.py:94} INFO - [0m04:25:21  1 of 1 OK created sql table model dwh.dim_products ............................. [[32mSUCCESS 1[0m in 3.25s]
[2024-07-14T04:25:21.852+0000] {subprocess.py:94} INFO - [0m04:25:21
[2024-07-14T04:25:21.865+0000] {subprocess.py:94} INFO - [0m04:25:21  Finished running 1 table model in 0 hours 0 minutes and 12.20 seconds (12.20s).
[2024-07-14T04:25:22.576+0000] {subprocess.py:94} INFO - [0m04:25:22
[2024-07-14T04:25:22.582+0000] {subprocess.py:94} INFO - [0m04:25:22  [32mCompleted successfully[0m
[2024-07-14T04:25:22.592+0000] {subprocess.py:94} INFO - [0m04:25:22
[2024-07-14T04:25:22.596+0000] {subprocess.py:94} INFO - [0m04:25:22  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:25:25.653+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:25:25.656+0000] {local.py:254} INFO - [0m04:25:22  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:25:27.520+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:25:27.536+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:25:27.566+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_categories', extra=None), Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_suppliers', extra=None), Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_products', extra=None)]
[2024-07-14T04:25:27.582+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_products', extra=None)]
[2024-07-14T04:25:27.592+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:25:28.251+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:25:28.648+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.dim_products.run, run_id=scheduled__2024-07-05T00:00:00+00:00, execution_date=20240705T000000, start_date=20240714T042420, end_date=20240714T042528
[2024-07-14T04:25:28.875+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:25:29.146+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:25:29.160+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
