[2024-07-14T04:18:28.181+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:18:28.352+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_suppliers.test scheduled__2024-07-03T00:00:00+00:00 [queued]>
[2024-07-14T04:18:28.473+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_suppliers.test scheduled__2024-07-03T00:00:00+00:00 [queued]>
[2024-07-14T04:18:28.478+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:18:28.612+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.dim_suppliers.test> on 2024-07-03 00:00:00+00:00
[2024-07-14T04:18:28.646+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=15681) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:18:28.659+0000] {standard_task_runner.py:63} INFO - Started process 15711 to run task
[2024-07-14T04:18:28.665+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.dim_suppliers.test', 'scheduled__2024-07-03T00:00:00+00:00', '--job-id', '1247', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpyia88rdp']
[2024-07-14T04:18:28.683+0000] {standard_task_runner.py:91} INFO - Job 1247: Subtask transform.dim_suppliers.test
[2024-07-14T04:18:28.817+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:18:29.244+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.dim_suppliers.test scheduled__2024-07-03T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:18:30.299+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.dim_suppliers.test' AIRFLOW_CTX_EXECUTION_DATE='2024-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-03T00:00:00+00:00'
[2024-07-14T04:18:30.305+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:18:30.311+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:18:30.332+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmp7c7_tnk3 from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:18:30.385+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:18:30.781+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:18:30.799+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:18:30.801+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:18:30.824+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:18:30.831+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp7c7_tnk3', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp7c7_tnk3
[2024-07-14T04:18:30.848+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:18:30.901+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp7c7_tnk3', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:18:30.999+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:18:48.512+0000] {subprocess.py:94} INFO - [0m04:18:48  Running with dbt=1.8.3
[2024-07-14T04:18:50.230+0000] {subprocess.py:94} INFO - [0m04:18:50  Updating lock file in file path: /tmp/tmp7c7_tnk3/package-lock.yml
[2024-07-14T04:18:50.298+0000] {subprocess.py:94} INFO - [0m04:18:50  Installing dbt-labs/dbt_utils
[2024-07-14T04:18:51.155+0000] {subprocess.py:94} INFO - [0m04:18:51  Installed from version 0.8.6
[2024-07-14T04:18:51.165+0000] {subprocess.py:94} INFO - [0m04:18:51  Updated version available: 1.2.0
[2024-07-14T04:18:51.171+0000] {subprocess.py:94} INFO - [0m04:18:51
[2024-07-14T04:18:51.175+0000] {subprocess.py:94} INFO - [0m04:18:51  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:18:51.177+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:18:54.763+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:18:54.768+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:18:54.775+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'dim_suppliers', '--project-dir', '/tmp/tmp7c7_tnk3', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp7c7_tnk3
[2024-07-14T04:18:54.790+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:18:54.812+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'dim_suppliers', '--project-dir', '/tmp/tmp7c7_tnk3', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:18:55.006+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:19:12.823+0000] {subprocess.py:94} INFO - [0m04:19:12  Running with dbt=1.8.3
[2024-07-14T04:19:16.725+0000] {subprocess.py:94} INFO - [0m04:19:16  Registered adapter: snowflake=1.8.3
[2024-07-14T04:19:22.211+0000] {subprocess.py:94} INFO - [0m04:19:22  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:19:22.229+0000] {subprocess.py:94} INFO - [0m04:19:22
[2024-07-14T04:19:28.892+0000] {subprocess.py:94} INFO - [0m04:19:28  Concurrency: 1 threads (target='dev')
[2024-07-14T04:19:28.896+0000] {subprocess.py:94} INFO - [0m04:19:28
[2024-07-14T04:19:28.986+0000] {subprocess.py:94} INFO - [0m04:19:28  1 of 1 START test not_null_dim_suppliers_SUPPLIERID ............................ [RUN]
[2024-07-14T04:19:31.007+0000] {subprocess.py:94} INFO - [0m04:19:31  1 of 1 PASS not_null_dim_suppliers_SUPPLIERID .................................. [[32mPASS[0m in 2.02s]
[2024-07-14T04:19:31.025+0000] {subprocess.py:94} INFO - [0m04:19:31
[2024-07-14T04:19:31.030+0000] {subprocess.py:94} INFO - [0m04:19:31  Finished running 1 test in 0 hours 0 minutes and 8.79 seconds (8.79s).
[2024-07-14T04:19:31.749+0000] {subprocess.py:94} INFO - [0m04:19:31
[2024-07-14T04:19:31.767+0000] {subprocess.py:94} INFO - [0m04:19:31  [32mCompleted successfully[0m
[2024-07-14T04:19:31.773+0000] {subprocess.py:94} INFO - [0m04:19:31
[2024-07-14T04:19:31.777+0000] {subprocess.py:94} INFO - [0m04:19:31  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:19:34.555+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:19:34.560+0000] {local.py:254} INFO - [0m04:19:31  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:19:35.564+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:19:35.580+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:19:35.613+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_suppliers', extra=None)]
[2024-07-14T04:19:35.615+0000] {local.py:350} INFO - Outlets: []
[2024-07-14T04:19:35.618+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:19:35.926+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:19:36.004+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.dim_suppliers.test, run_id=scheduled__2024-07-03T00:00:00+00:00, execution_date=20240703T000000, start_date=20240714T041828, end_date=20240714T041936
[2024-07-14T04:19:36.487+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:19:36.845+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:19:36.855+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
