[2024-07-14T04:10:15.941+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:10:16.075+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_products.run scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-07-14T04:10:16.236+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_products.run scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-07-14T04:10:16.239+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:10:16.303+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.raw_products.run> on 2024-06-27 00:00:00+00:00
[2024-07-14T04:10:16.360+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=13911) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:10:16.366+0000] {standard_task_runner.py:63} INFO - Started process 13949 to run task
[2024-07-14T04:10:16.369+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_products.run', 'scheduled__2024-06-27T00:00:00+00:00', '--job-id', '1139', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpygrbyw0w']
[2024-07-14T04:10:16.387+0000] {standard_task_runner.py:91} INFO - Job 1139: Subtask transform.raw_products.run
[2024-07-14T04:10:16.470+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:10:16.762+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_products.run scheduled__2024-06-27T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:10:17.158+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_products.run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:00:00+00:00'
[2024-07-14T04:10:17.175+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:10:17.197+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:10:17.202+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpxvs7nnnt from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:10:17.219+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:10:17.407+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:10:17.409+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:10:17.411+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:10:17.439+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:10:17.471+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpxvs7nnnt', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpxvs7nnnt
[2024-07-14T04:10:17.498+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:10:17.508+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpxvs7nnnt', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:10:17.572+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:10:28.372+0000] {subprocess.py:94} INFO - [0m04:10:28  Running with dbt=1.8.3
[2024-07-14T04:10:29.726+0000] {subprocess.py:94} INFO - [0m04:10:29  Updating lock file in file path: /tmp/tmpxvs7nnnt/package-lock.yml
[2024-07-14T04:10:29.780+0000] {subprocess.py:94} INFO - [0m04:10:29  Installing dbt-labs/dbt_utils
[2024-07-14T04:10:30.542+0000] {subprocess.py:94} INFO - [0m04:10:30  Installed from version 0.8.6
[2024-07-14T04:10:30.549+0000] {subprocess.py:94} INFO - [0m04:10:30  Updated version available: 1.2.0
[2024-07-14T04:10:30.558+0000] {subprocess.py:94} INFO - [0m04:10:30
[2024-07-14T04:10:30.562+0000] {subprocess.py:94} INFO - [0m04:10:30  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:10:30.564+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:10:32.593+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:10:32.596+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:10:32.598+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_products', '--project-dir', '/tmp/tmpxvs7nnnt', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpxvs7nnnt
[2024-07-14T04:10:32.601+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:10:32.603+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_products', '--project-dir', '/tmp/tmpxvs7nnnt', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:10:32.678+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:10:47.126+0000] {subprocess.py:94} INFO - [0m04:10:47  Running with dbt=1.8.3
[2024-07-14T04:10:52.010+0000] {subprocess.py:94} INFO - [0m04:10:52  Registered adapter: snowflake=1.8.3
[2024-07-14T04:10:57.377+0000] {subprocess.py:94} INFO - [0m04:10:57  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:10:57.390+0000] {subprocess.py:94} INFO - [0m04:10:57
[2024-07-14T04:11:05.634+0000] {subprocess.py:94} INFO - [0m04:11:05  Concurrency: 1 threads (target='dev')
[2024-07-14T04:11:05.640+0000] {subprocess.py:94} INFO - [0m04:11:05
[2024-07-14T04:11:05.850+0000] {subprocess.py:94} INFO - [0m04:11:05  1 of 1 START sql table model raw.raw_products .................................. [RUN]
[2024-07-14T04:11:08.959+0000] {subprocess.py:94} INFO - [0m04:11:08  1 of 1 OK created sql table model raw.raw_products ............................. [[32mSUCCESS 1[0m in 3.10s]
[2024-07-14T04:11:08.997+0000] {subprocess.py:94} INFO - [0m04:11:08
[2024-07-14T04:11:08.999+0000] {subprocess.py:94} INFO - [0m04:11:08  Finished running 1 table model in 0 hours 0 minutes and 11.60 seconds (11.60s).
[2024-07-14T04:11:09.724+0000] {subprocess.py:94} INFO - [0m04:11:09
[2024-07-14T04:11:09.728+0000] {subprocess.py:94} INFO - [0m04:11:09  [32mCompleted successfully[0m
[2024-07-14T04:11:09.731+0000] {subprocess.py:94} INFO - [0m04:11:09
[2024-07-14T04:11:09.737+0000] {subprocess.py:94} INFO - [0m04:11:09  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:11:12.654+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:11:12.656+0000] {local.py:254} INFO - [0m04:11:09  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:11:13.967+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:11:13.975+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:11:14.002+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.PUBLIC.products', extra=None)]
[2024-07-14T04:11:14.017+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_products', extra=None)]
[2024-07-14T04:11:14.036+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:11:14.446+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:11:14.726+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_products.run, run_id=scheduled__2024-06-27T00:00:00+00:00, execution_date=20240627T000000, start_date=20240714T041016, end_date=20240714T041114
[2024-07-14T04:11:16.113+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:11:16.275+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
