[2024-07-14T04:20:37.873+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:20:38.049+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_suppliers.test scheduled__2024-07-07T00:00:00+00:00 [queued]>
[2024-07-14T04:20:38.125+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_suppliers.test scheduled__2024-07-07T00:00:00+00:00 [queued]>
[2024-07-14T04:20:38.127+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:20:38.228+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.dim_suppliers.test> on 2024-07-07 00:00:00+00:00
[2024-07-14T04:20:38.264+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=16110) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:20:38.268+0000] {standard_task_runner.py:63} INFO - Started process 16135 to run task
[2024-07-14T04:20:38.288+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.dim_suppliers.test', 'scheduled__2024-07-07T00:00:00+00:00', '--job-id', '1270', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp8v_i65mg']
[2024-07-14T04:20:38.293+0000] {standard_task_runner.py:91} INFO - Job 1270: Subtask transform.dim_suppliers.test
[2024-07-14T04:20:38.384+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:20:38.741+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.dim_suppliers.test scheduled__2024-07-07T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:20:39.257+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.dim_suppliers.test' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-07T00:00:00+00:00'
[2024-07-14T04:20:39.266+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:20:39.279+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:20:39.301+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmptgmfien5 from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:20:39.338+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:20:39.518+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:20:39.523+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:20:39.531+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:20:39.549+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:20:39.555+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmptgmfien5', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmptgmfien5
[2024-07-14T04:20:39.561+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:20:39.564+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmptgmfien5', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:20:39.615+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:20:54.803+0000] {subprocess.py:94} INFO - [0m04:20:54  Running with dbt=1.8.3
[2024-07-14T04:20:56.786+0000] {subprocess.py:94} INFO - [0m04:20:56  Updating lock file in file path: /tmp/tmptgmfien5/package-lock.yml
[2024-07-14T04:20:56.879+0000] {subprocess.py:94} INFO - [0m04:20:56  Installing dbt-labs/dbt_utils
[2024-07-14T04:20:57.723+0000] {subprocess.py:94} INFO - [0m04:20:57  Installed from version 0.8.6
[2024-07-14T04:20:57.727+0000] {subprocess.py:94} INFO - [0m04:20:57  Updated version available: 1.2.0
[2024-07-14T04:20:57.737+0000] {subprocess.py:94} INFO - [0m04:20:57
[2024-07-14T04:20:57.741+0000] {subprocess.py:94} INFO - [0m04:20:57  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:20:57.744+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:21:00.822+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:21:00.825+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:21:00.828+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'dim_suppliers', '--project-dir', '/tmp/tmptgmfien5', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmptgmfien5
[2024-07-14T04:21:00.832+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:21:00.835+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'dim_suppliers', '--project-dir', '/tmp/tmptgmfien5', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:21:00.888+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:21:18.098+0000] {subprocess.py:94} INFO - [0m04:21:18  Running with dbt=1.8.3
[2024-07-14T04:21:22.878+0000] {subprocess.py:94} INFO - [0m04:21:22  Registered adapter: snowflake=1.8.3
[2024-07-14T04:21:29.002+0000] {subprocess.py:94} INFO - [0m04:21:29  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:21:29.013+0000] {subprocess.py:94} INFO - [0m04:21:29
[2024-07-14T04:21:35.663+0000] {subprocess.py:94} INFO - [0m04:21:35  Concurrency: 1 threads (target='dev')
[2024-07-14T04:21:35.667+0000] {subprocess.py:94} INFO - [0m04:21:35
[2024-07-14T04:21:35.835+0000] {subprocess.py:94} INFO - [0m04:21:35  1 of 1 START test not_null_dim_suppliers_SUPPLIERID ............................ [RUN]
[2024-07-14T04:21:38.031+0000] {subprocess.py:94} INFO - [0m04:21:38  1 of 1 PASS not_null_dim_suppliers_SUPPLIERID .................................. [[32mPASS[0m in 2.20s]
[2024-07-14T04:21:38.058+0000] {subprocess.py:94} INFO - [0m04:21:38
[2024-07-14T04:21:38.063+0000] {subprocess.py:94} INFO - [0m04:21:38  Finished running 1 test in 0 hours 0 minutes and 9.04 seconds (9.04s).
[2024-07-14T04:21:38.724+0000] {subprocess.py:94} INFO - [0m04:21:38
[2024-07-14T04:21:38.730+0000] {subprocess.py:94} INFO - [0m04:21:38  [32mCompleted successfully[0m
[2024-07-14T04:21:38.733+0000] {subprocess.py:94} INFO - [0m04:21:38
[2024-07-14T04:21:38.736+0000] {subprocess.py:94} INFO - [0m04:21:38  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:21:41.434+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:21:41.436+0000] {local.py:254} INFO - [0m04:21:38  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:21:42.320+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:21:42.326+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:21:42.351+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_suppliers', extra=None)]
[2024-07-14T04:21:42.359+0000] {local.py:350} INFO - Outlets: []
[2024-07-14T04:21:42.406+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:21:42.966+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:21:43.173+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.dim_suppliers.test, run_id=scheduled__2024-07-07T00:00:00+00:00, execution_date=20240707T000000, start_date=20240714T042038, end_date=20240714T042143
[2024-07-14T04:21:44.626+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:21:45.050+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:21:45.112+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
