[2024-07-14T04:09:26.360+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:09:26.476+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_employees.test scheduled__2024-07-10T00:00:00+00:00 [queued]>
[2024-07-14T04:09:26.662+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_employees.test scheduled__2024-07-10T00:00:00+00:00 [queued]>
[2024-07-14T04:09:26.672+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:09:26.855+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.raw_employees.test> on 2024-07-10 00:00:00+00:00
[2024-07-14T04:09:26.880+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_employees.test', 'scheduled__2024-07-10T00:00:00+00:00', '--job-id', '1126', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpn_hyla1a']
[2024-07-14T04:09:26.900+0000] {standard_task_runner.py:91} INFO - Job 1126: Subtask transform.raw_employees.test
[2024-07-14T04:09:26.897+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=13755) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:09:26.917+0000] {standard_task_runner.py:63} INFO - Started process 13785 to run task
[2024-07-14T04:09:26.989+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:09:27.326+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_employees.test scheduled__2024-07-10T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:09:28.061+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_employees.test' AIRFLOW_CTX_EXECUTION_DATE='2024-07-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-10T00:00:00+00:00'
[2024-07-14T04:09:28.064+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:09:28.071+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:09:28.085+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmp22ctfq3d from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:09:28.147+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:09:28.322+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:09:28.329+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:09:28.331+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:09:28.353+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:09:28.357+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp22ctfq3d', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp22ctfq3d
[2024-07-14T04:09:28.363+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:09:28.373+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp22ctfq3d', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:09:28.445+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:09:43.015+0000] {subprocess.py:94} INFO - [0m04:09:43  Running with dbt=1.8.3
[2024-07-14T04:09:45.027+0000] {subprocess.py:94} INFO - [0m04:09:45  Updating lock file in file path: /tmp/tmp22ctfq3d/package-lock.yml
[2024-07-14T04:09:45.087+0000] {subprocess.py:94} INFO - [0m04:09:45  Installing dbt-labs/dbt_utils
[2024-07-14T04:09:46.246+0000] {subprocess.py:94} INFO - [0m04:09:46  Installed from version 0.8.6
[2024-07-14T04:09:46.253+0000] {subprocess.py:94} INFO - [0m04:09:46  Updated version available: 1.2.0
[2024-07-14T04:09:46.270+0000] {subprocess.py:94} INFO - [0m04:09:46
[2024-07-14T04:09:46.273+0000] {subprocess.py:94} INFO - [0m04:09:46  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:09:46.304+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:09:48.932+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:09:48.934+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:09:48.936+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_employees', '--project-dir', '/tmp/tmp22ctfq3d', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp22ctfq3d
[2024-07-14T04:09:48.938+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:09:48.946+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_employees', '--project-dir', '/tmp/tmp22ctfq3d', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:09:49.097+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:10:03.276+0000] {subprocess.py:94} INFO - [0m04:10:03  Running with dbt=1.8.3
[2024-07-14T04:10:07.079+0000] {subprocess.py:94} INFO - [0m04:10:07  Registered adapter: snowflake=1.8.3
[2024-07-14T04:10:14.481+0000] {subprocess.py:94} INFO - [0m04:10:14  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:10:14.497+0000] {subprocess.py:94} INFO - [0m04:10:14
[2024-07-14T04:10:21.174+0000] {subprocess.py:94} INFO - [0m04:10:21  Concurrency: 1 threads (target='dev')
[2024-07-14T04:10:21.177+0000] {subprocess.py:94} INFO - [0m04:10:21
[2024-07-14T04:10:21.325+0000] {subprocess.py:94} INFO - [0m04:10:21  1 of 1 START test not_null_raw_employees_EMPLOYEEID ............................ [RUN]
[2024-07-14T04:10:23.388+0000] {subprocess.py:94} INFO - [0m04:10:23  1 of 1 PASS not_null_raw_employees_EMPLOYEEID .................................. [[32mPASS[0m in 2.06s]
[2024-07-14T04:10:23.411+0000] {subprocess.py:94} INFO - [0m04:10:23
[2024-07-14T04:10:23.415+0000] {subprocess.py:94} INFO - [0m04:10:23  Finished running 1 test in 0 hours 0 minutes and 8.91 seconds (8.91s).
[2024-07-14T04:10:24.168+0000] {subprocess.py:94} INFO - [0m04:10:24
[2024-07-14T04:10:24.188+0000] {subprocess.py:94} INFO - [0m04:10:24  [32mCompleted successfully[0m
[2024-07-14T04:10:24.193+0000] {subprocess.py:94} INFO - [0m04:10:24
[2024-07-14T04:10:24.197+0000] {subprocess.py:94} INFO - [0m04:10:24  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:10:26.781+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:10:26.783+0000] {local.py:254} INFO - [0m04:10:24  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:10:27.729+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:10:27.732+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:10:27.751+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_employees', extra=None)]
[2024-07-14T04:10:27.777+0000] {local.py:350} INFO - Outlets: []
[2024-07-14T04:10:27.780+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:10:28.093+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:10:28.233+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_employees.test, run_id=scheduled__2024-07-10T00:00:00+00:00, execution_date=20240710T000000, start_date=20240714T040926, end_date=20240714T041028
[2024-07-14T04:10:28.886+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:10:28.961+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
