[2024-07-14T04:24:38.515+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:24:38.643+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_products.run scheduled__2024-07-06T00:00:00+00:00 [queued]>
[2024-07-14T04:24:38.744+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_products.run scheduled__2024-07-06T00:00:00+00:00 [queued]>
[2024-07-14T04:24:38.746+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:24:38.888+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.dim_products.run> on 2024-07-06 00:00:00+00:00
[2024-07-14T04:24:38.912+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=16968) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:24:38.937+0000] {standard_task_runner.py:63} INFO - Started process 17008 to run task
[2024-07-14T04:24:38.917+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.dim_products.run', 'scheduled__2024-07-06T00:00:00+00:00', '--job-id', '1324', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpxwa3u05d']
[2024-07-14T04:24:38.957+0000] {standard_task_runner.py:91} INFO - Job 1324: Subtask transform.dim_products.run
[2024-07-14T04:24:39.037+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:24:39.273+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.dim_products.run scheduled__2024-07-06T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:24:39.955+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.dim_products.run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-06T00:00:00+00:00'
[2024-07-14T04:24:39.965+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:24:39.978+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:24:39.992+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmp2ir90ncl from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:24:40.011+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:24:40.186+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:24:40.188+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:24:40.189+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:24:40.222+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:24:40.225+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp2ir90ncl', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp2ir90ncl
[2024-07-14T04:24:40.241+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:24:40.265+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp2ir90ncl', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:24:40.337+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:24:58.546+0000] {subprocess.py:94} INFO - [0m04:24:58  Running with dbt=1.8.3
[2024-07-14T04:25:01.205+0000] {subprocess.py:94} INFO - [0m04:25:01  Updating lock file in file path: /tmp/tmp2ir90ncl/package-lock.yml
[2024-07-14T04:25:01.313+0000] {subprocess.py:94} INFO - [0m04:25:01  Installing dbt-labs/dbt_utils
[2024-07-14T04:25:02.153+0000] {subprocess.py:94} INFO - [0m04:25:02  Installed from version 0.8.6
[2024-07-14T04:25:02.166+0000] {subprocess.py:94} INFO - [0m04:25:02  Updated version available: 1.2.0
[2024-07-14T04:25:02.189+0000] {subprocess.py:94} INFO - [0m04:25:02
[2024-07-14T04:25:02.196+0000] {subprocess.py:94} INFO - [0m04:25:02  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:25:02.198+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:25:04.332+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:25:04.335+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:25:04.340+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'dim_products', '--project-dir', '/tmp/tmp2ir90ncl', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp2ir90ncl
[2024-07-14T04:25:04.364+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:25:04.370+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'dim_products', '--project-dir', '/tmp/tmp2ir90ncl', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:25:04.457+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:25:20.843+0000] {subprocess.py:94} INFO - [0m04:25:20  Running with dbt=1.8.3
[2024-07-14T04:25:24.180+0000] {subprocess.py:94} INFO - [0m04:25:24  Registered adapter: snowflake=1.8.3
[2024-07-14T04:25:31.103+0000] {subprocess.py:94} INFO - [0m04:25:31  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:25:31.117+0000] {subprocess.py:94} INFO - [0m04:25:31
[2024-07-14T04:25:39.133+0000] {subprocess.py:94} INFO - [0m04:25:39  Concurrency: 1 threads (target='dev')
[2024-07-14T04:25:39.136+0000] {subprocess.py:94} INFO - [0m04:25:39
[2024-07-14T04:25:39.331+0000] {subprocess.py:94} INFO - [0m04:25:39  1 of 1 START sql table model dwh.dim_products .................................. [RUN]
[2024-07-14T04:25:42.693+0000] {subprocess.py:94} INFO - [0m04:25:42  1 of 1 OK created sql table model dwh.dim_products ............................. [[32mSUCCESS 1[0m in 3.35s]
[2024-07-14T04:25:42.725+0000] {subprocess.py:94} INFO - [0m04:25:42
[2024-07-14T04:25:42.729+0000] {subprocess.py:94} INFO - [0m04:25:42  Finished running 1 table model in 0 hours 0 minutes and 11.60 seconds (11.60s).
[2024-07-14T04:25:43.608+0000] {subprocess.py:94} INFO - [0m04:25:43
[2024-07-14T04:25:43.621+0000] {subprocess.py:94} INFO - [0m04:25:43  [32mCompleted successfully[0m
[2024-07-14T04:25:43.639+0000] {subprocess.py:94} INFO - [0m04:25:43
[2024-07-14T04:25:43.644+0000] {subprocess.py:94} INFO - [0m04:25:43  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:25:46.292+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:25:46.294+0000] {local.py:254} INFO - [0m04:25:43  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:25:47.495+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:25:47.516+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:25:47.594+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_categories', extra=None), Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_suppliers', extra=None), Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_products', extra=None)]
[2024-07-14T04:25:47.610+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_products', extra=None)]
[2024-07-14T04:25:47.617+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:25:48.042+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:25:48.412+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.dim_products.run, run_id=scheduled__2024-07-06T00:00:00+00:00, execution_date=20240706T000000, start_date=20240714T042438, end_date=20240714T042548
[2024-07-14T04:25:48.593+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:25:48.677+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
