[2024-07-14T04:37:46.151+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:37:46.367+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_shippers.run scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-14T04:37:46.458+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_shippers.run scheduled__2024-07-11T00:00:00+00:00 [queued]>
[2024-07-14T04:37:46.466+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:37:46.533+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.raw_shippers.run> on 2024-07-11 00:00:00+00:00
[2024-07-14T04:37:46.553+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=19627) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:37:46.566+0000] {standard_task_runner.py:63} INFO - Started process 19652 to run task
[2024-07-14T04:37:46.573+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_shippers.run', 'scheduled__2024-07-11T00:00:00+00:00', '--job-id', '1483', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp_0f_zb3v']
[2024-07-14T04:37:46.595+0000] {standard_task_runner.py:91} INFO - Job 1483: Subtask transform.raw_shippers.run
[2024-07-14T04:37:46.674+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:37:47.093+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_shippers.run scheduled__2024-07-11T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:37:47.878+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_shippers.run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T00:00:00+00:00'
[2024-07-14T04:37:47.899+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:37:47.922+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:37:47.940+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpsxasblk6 from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:37:47.989+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:37:48.307+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:37:48.328+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:37:48.333+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:37:48.345+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:37:48.351+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpsxasblk6', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpsxasblk6
[2024-07-14T04:37:48.357+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:37:48.422+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpsxasblk6', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:37:48.527+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:38:04.503+0000] {subprocess.py:94} INFO - [0m04:38:04  Running with dbt=1.8.3
[2024-07-14T04:38:06.265+0000] {subprocess.py:94} INFO - [0m04:38:06  Updating lock file in file path: /tmp/tmpsxasblk6/package-lock.yml
[2024-07-14T04:38:06.339+0000] {subprocess.py:94} INFO - [0m04:38:06  Installing dbt-labs/dbt_utils
[2024-07-14T04:38:07.237+0000] {subprocess.py:94} INFO - [0m04:38:07  Installed from version 0.8.6
[2024-07-14T04:38:07.241+0000] {subprocess.py:94} INFO - [0m04:38:07  Updated version available: 1.2.0
[2024-07-14T04:38:07.269+0000] {subprocess.py:94} INFO - [0m04:38:07
[2024-07-14T04:38:07.277+0000] {subprocess.py:94} INFO - [0m04:38:07  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:38:07.284+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:38:09.363+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:38:09.370+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:38:09.372+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_shippers', '--project-dir', '/tmp/tmpsxasblk6', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpsxasblk6
[2024-07-14T04:38:09.378+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:38:09.388+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_shippers', '--project-dir', '/tmp/tmpsxasblk6', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:38:09.489+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:38:23.027+0000] {subprocess.py:94} INFO - [0m04:38:23  Running with dbt=1.8.3
[2024-07-14T04:38:27.826+0000] {subprocess.py:94} INFO - [0m04:38:27  Registered adapter: snowflake=1.8.3
[2024-07-14T04:38:33.027+0000] {subprocess.py:94} INFO - [0m04:38:33  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:38:33.063+0000] {subprocess.py:94} INFO - [0m04:38:33
[2024-07-14T04:38:42.206+0000] {subprocess.py:94} INFO - [0m04:38:42  Concurrency: 1 threads (target='dev')
[2024-07-14T04:38:42.208+0000] {subprocess.py:94} INFO - [0m04:38:42
[2024-07-14T04:38:42.510+0000] {subprocess.py:94} INFO - [0m04:38:42  1 of 1 START sql table model raw.raw_shippers .................................. [RUN]
[2024-07-14T04:38:46.041+0000] {subprocess.py:94} INFO - [0m04:38:46  1 of 1 OK created sql table model raw.raw_shippers ............................. [[32mSUCCESS 1[0m in 3.52s]
[2024-07-14T04:38:46.067+0000] {subprocess.py:94} INFO - [0m04:38:46
[2024-07-14T04:38:46.070+0000] {subprocess.py:94} INFO - [0m04:38:46  Finished running 1 table model in 0 hours 0 minutes and 13.00 seconds (13.00s).
[2024-07-14T04:38:47.008+0000] {subprocess.py:94} INFO - [0m04:38:47
[2024-07-14T04:38:47.018+0000] {subprocess.py:94} INFO - [0m04:38:47  [32mCompleted successfully[0m
[2024-07-14T04:38:47.022+0000] {subprocess.py:94} INFO - [0m04:38:47
[2024-07-14T04:38:47.029+0000] {subprocess.py:94} INFO - [0m04:38:47  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:38:49.588+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:38:49.594+0000] {local.py:254} INFO - [0m04:38:47  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:38:50.708+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:38:50.711+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:38:50.744+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.PUBLIC.shippers', extra=None)]
[2024-07-14T04:38:50.750+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_shippers', extra=None)]
[2024-07-14T04:38:50.752+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:38:51.084+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:38:51.360+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_shippers.run, run_id=scheduled__2024-07-11T00:00:00+00:00, execution_date=20240711T000000, start_date=20240714T043746, end_date=20240714T043851
[2024-07-14T04:38:51.726+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:38:51.984+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:38:52.008+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
