[2024-07-14T04:46:03.414+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:46:03.631+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_territories.test scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-07-14T04:46:03.745+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_territories.test scheduled__2024-07-05T00:00:00+00:00 [queued]>
[2024-07-14T04:46:03.753+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:46:03.825+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.raw_territories.test> on 2024-07-05 00:00:00+00:00
[2024-07-14T04:46:03.896+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_territories.test', 'scheduled__2024-07-05T00:00:00+00:00', '--job-id', '1602', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp_qkfa1f0']
[2024-07-14T04:46:03.903+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=21419) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:46:03.924+0000] {standard_task_runner.py:63} INFO - Started process 21444 to run task
[2024-07-14T04:46:03.930+0000] {standard_task_runner.py:91} INFO - Job 1602: Subtask transform.raw_territories.test
[2024-07-14T04:46:04.071+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:46:04.651+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_territories.test scheduled__2024-07-05T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:46:06.207+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_territories.test' AIRFLOW_CTX_EXECUTION_DATE='2024-07-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-05T00:00:00+00:00'
[2024-07-14T04:46:06.229+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:46:06.265+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:46:06.289+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpk55bodz5 from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:46:06.393+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:46:08.364+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:46:08.394+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:46:08.412+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:46:08.434+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:46:08.466+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpk55bodz5', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpk55bodz5
[2024-07-14T04:46:08.483+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:46:08.502+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpk55bodz5', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:46:08.653+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:46:24.444+0000] {subprocess.py:94} INFO - [0m04:46:24  Running with dbt=1.8.3
[2024-07-14T04:46:26.014+0000] {subprocess.py:94} INFO - [0m04:46:26  Updating lock file in file path: /tmp/tmpk55bodz5/package-lock.yml
[2024-07-14T04:46:26.081+0000] {subprocess.py:94} INFO - [0m04:46:26  Installing dbt-labs/dbt_utils
[2024-07-14T04:46:26.926+0000] {subprocess.py:94} INFO - [0m04:46:26  Installed from version 0.8.6
[2024-07-14T04:46:26.935+0000] {subprocess.py:94} INFO - [0m04:46:26  Updated version available: 1.2.0
[2024-07-14T04:46:26.947+0000] {subprocess.py:94} INFO - [0m04:46:26
[2024-07-14T04:46:26.955+0000] {subprocess.py:94} INFO - [0m04:46:26  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:46:26.956+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:46:29.293+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:46:29.296+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:46:29.298+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_territories', '--project-dir', '/tmp/tmpk55bodz5', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpk55bodz5
[2024-07-14T04:46:29.300+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:46:29.302+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_territories', '--project-dir', '/tmp/tmpk55bodz5', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:46:29.362+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:46:40.727+0000] {subprocess.py:94} INFO - [0m04:46:40  Running with dbt=1.8.3
[2024-07-14T04:46:44.130+0000] {subprocess.py:94} INFO - [0m04:46:44  Registered adapter: snowflake=1.8.3
[2024-07-14T04:46:49.002+0000] {subprocess.py:94} INFO - [0m04:46:49  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:46:49.032+0000] {subprocess.py:94} INFO - [0m04:46:49
[2024-07-14T04:46:55.581+0000] {subprocess.py:94} INFO - [0m04:46:55  Concurrency: 1 threads (target='dev')
[2024-07-14T04:46:55.592+0000] {subprocess.py:94} INFO - [0m04:46:55
[2024-07-14T04:46:55.733+0000] {subprocess.py:94} INFO - [0m04:46:55  1 of 1 START test not_null_raw_territories_TERRITORYID ......................... [RUN]
[2024-07-14T04:47:02.199+0000] {subprocess.py:94} INFO - [0m04:47:02  1 of 1 PASS not_null_raw_territories_TERRITORYID ............................... [[32mPASS[0m in 6.46s]
[2024-07-14T04:47:02.234+0000] {subprocess.py:94} INFO - [0m04:47:02
[2024-07-14T04:47:02.240+0000] {subprocess.py:94} INFO - [0m04:47:02  Finished running 1 test in 0 hours 0 minutes and 13.20 seconds (13.20s).
[2024-07-14T04:47:02.808+0000] {subprocess.py:94} INFO - [0m04:47:02
[2024-07-14T04:47:02.810+0000] {subprocess.py:94} INFO - [0m04:47:02  [32mCompleted successfully[0m
[2024-07-14T04:47:02.815+0000] {subprocess.py:94} INFO - [0m04:47:02
[2024-07-14T04:47:02.817+0000] {subprocess.py:94} INFO - [0m04:47:02  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:47:05.793+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:47:05.795+0000] {local.py:254} INFO - [0m04:47:02  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:47:05.982+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:47:05.987+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:47:06.031+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_territories', extra=None)]
[2024-07-14T04:47:06.035+0000] {local.py:350} INFO - Outlets: []
[2024-07-14T04:47:06.070+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:47:06.357+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to 2024-07-14 00:00:00+00:00, run_after=2024-07-15 00:00:00+00:00
[2024-07-14T04:47:06.714+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:47:07.242+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_territories.test, run_id=scheduled__2024-07-05T00:00:00+00:00, execution_date=20240705T000000, start_date=20240714T044603, end_date=20240714T044707
[2024-07-14T04:47:07.633+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:47:07.966+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:47:08.001+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
